apiVersion: v1
kind: Service
metadata:
  name: hivemq-web-ui
spec:
  type: LoadBalancer
  selector:
      app.kubernetes.io/instance: test-hivemq-platform
      app.kubernetes.io/name: hivemq-platform
  ports:
    - protocol: TCP
      port: 8080       # exposed port
      targetPort: 8080 # container port for Web UI
  sessionAffinity: ClientIP
