name: Push-triggered Workflow

on:
  push:
    branches:
      - main

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Print kubectl version
        run: kubectl version --client

      - name: Print Helm version
        run: helm version

      - name: Print commit info
        run: |
          echo "Pushed branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Pusher: ${{ github.actor }}"

