name: Push-triggered Workflow

on:
  push:
    branches:
      - main

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print commit info
        run: |
          echo "Pushed branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Pusher: ${{ github.actor }}"

