name: Deploy HiveMQ to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Upgrade/install HiveMQ with Helm
        run: |
          helm repo add hivemq https://hivemq.github.io/helm-charts
          helm repo update
          helm upgrade --install test-hivemq-platform hivemq/hivemq-platform \
            -n hivetest --create-namespace \
            --values helm/values.yaml

      - name: Apply custom services or manifests (optional)
        run: |
          kubectl apply -f kubernetes/hivemq-web-ui-service.yaml -n hivetest
