name: Deploy HiveMQ Platform via Helm

on:
  push:
    branches:
      - main

jobs:
  deploy-hivemq:
    name: Deploy HiveMQ Platform
    runs-on: self-hosted   # Must be your local runner with k8s access
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Configure kubeconfig from base64 secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config

      - name: Create 'hivemq' namespace if missing
        run: kubectl create namespace hivemq --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy HiveMQ Platform Helm Chart
        run: |
          helm upgrade --install hivemq-platform ./charts/hivemq-platform \
            -n hivemq --create-namespace -f ./charts/hivemq-platform/values.yaml

      - name: Verify HiveMQ deployment pods
        run: kubectl get pods -n hivemq
